# Generated by Django 5.1.4 on 2025-01-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='', upload_to=None),
            preserve_default=False,
        ),
    ]
