# Generated by Django 5.1.4 on 2025-01-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_img',
        ),
    ]
