# Generated by Django 5.1.4 on 2025-01-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_remove_product_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='', upload_to='upload'),
            preserve_default=False,
        ),
    ]
